admnetworking/urls.py
from django.contrib import admin
from django.urls import path
from accounts import views

urlpatterns = [
    path('admin/', admin.site.urls, name='house'),
    path('', views.home_view, name='home'),
    path('login/', views.LoginPage, name='login'),
    path('logout/', views.LogoutUser, name='logout'),
    path('registration/', views.registration, name='Registrar'),
    path('dashboard', views.HomeSystem, name='Dashboard'),
    path('guia-4to6/', views.Ipv4Ipv6intro, name='guia'),
    path('guia-4to6/pasos/', views.Ipv4Ipv6pasos, name='pasos'),
    path('guia-4to6/segmentacion/', views.SegmentacionCalculadoraipv6, name='segmento6'),
    path('calculadora-segmento/',views.SegmentacionCalculadora, name='segmento'),
    path('solicitud-usuario/', views.Solicitudcrear, name='crear solicitud'),
    path('solicitud-usuario/<int:pk>', views.Solicitudver, name='solicitudes de usuarios'),
    path('dispositivo/', views.InventarioListaDevice, name='Inventario'),
    path('dispositivo/crear', views.InventarioCrear, name='crear dispositivo'),
    path('dispositivo/<int:pk>/', views.InventarioUpdates, name='editar dispositivo'),
    path('ip/', views.IPListaReverse, name='ip'),
    path('ip/crear', views.IPCrear, name='crear ip'),
    path('ip/<int:pk>/', views.IPUpdates, name='editar ip'),
    path('ubicacion/', views.UbicacionLista, name='Lista Ubicacion'),
    path('ubicacion/crear', views.UbicacionCrear, name='Crear Ubicacion'),
    path('ubicacion/<int:pk>/', views.UbicacionUpdate, name='Editar Ubicacion'),
    path('ubicacion/<int:pk>/b', views.UbicacionBorrar, name='Borrar Ubicacion'),
    path('sendconf/', views.SendConfiguration, name='sendconf'),
    path('solicitud-usuario-f/<int:pk>/', views.Solicitudf, name='Solicitud Cambio'),
    path('inventario/<int:pk>/b', views.InventarioBorrar, name='Borrar Dispositivo'),
    path('ip/<int:pk>/b', views.IPBorrar, name='Borrar Ip'),

]

accounts/models.py
from django.db import models
from netaddr import *
import uuid
import pprint

# Inventario View
class Ubicacion(models.Model):
    localidad = models.CharField(max_length=50)
    departamento = models.CharField(max_length=50, blank=True, null=True)


#ParentModel.objects.exclude(childrenmodel_set__isnull=True)
# Inventario, SendConf View
class Device(models.Model):
    ROUTER = 'R'
    SWITCH = 'SW'
    FIREWALL = 'F'
    SERVIDOR = 'SR'
    ROUTERW = 'RW'
    ENDEV = 'ED'
    Type_Devices = [
        ('R', 'Router'),
        ('S', 'Switch'),
        ('F', 'Firewall'),
        ('SR', 'Servidor'),
        ('RW', 'Router WIFI'),
        ('ED', 'End Device'),

    ]
    #id = models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False)
    dvt =  models.CharField(max_length=2,choices=Type_Devices, verbose_name='Tipo de Dispositivos')
    ipv4 = models.GenericIPAddressField(protocol='IPv4', verbose_name='IPv4')
    ipv6 = models.GenericIPAddressField(protocol='IPv6',verbose_name='IPv6')
    ssh = models.BooleanField(blank=True, null=True, verbose_name='SSH')
    telnet = models.BooleanField(blank=True, null=True, verbose_name='Telnet')
    conf = models.FileField(upload_to='media/',blank=True, null=True, verbose_name='Archivo')
    conf_t = models.TextField(blank=True, null=True, verbose_name='Configuracion')
    username = models.CharField(max_length=50, verbose_name='Usuario de Acceso', blank=True, null=True)
    clave = models.CharField(max_length=50, verbose_name='Clave de Acceso', blank=True, null=True)
    name = models.CharField(max_length=50, verbose_name='Hostname',blank=True, null=True)
    ubicacion = models.ForeignKey(Ubicacion, on_delete=models.CASCADE, blank=True, null=True, verbose_name='Ubicacion del Equipo')
    modelo = models.CharField(max_length=50, blank=True, null=True, verbose_name='Modelo')
    serial = models.CharField(max_length=50, blank=True, null=True, verbose_name='Serial')
    marca = models.CharField(max_length=50, blank=True, null=True, verbose_name='Marca')
    responsable = models.CharField(max_length=50, blank=True, null=True, verbose_name='Responsable')

    def __str__(self):
        return '%s, %s'%(self.get_dvt_display(), self.ipv4)


# Inventario,SendConf View
class Puerto(models.Model):
    device = models.ForeignKey(Device, on_delete=models.CASCADE, blank=True, null=True, verbose_name='Dispositivo')
    puerto = models.CharField(max_length=50,blank=True, null=True, verbose_name='Puerto')
    vlan = models.IntegerField(default=1,blank=True, null=True, verbose_name='Vlan')
    mac = models.CharField(max_length=50,blank=True, null=True, verbose_name='Mac')
    ipv4 = models.GenericIPAddressField(protocol='IPv4', verbose_name='IPv4',blank=True, null=True)
    ipv6 = models.GenericIPAddressField(protocol='IPv6',verbose_name='IPv6',blank=True, null=True)
    actv = models.BooleanField(default=False, verbose_name='Puerto Activo')


#Logs
class Log(models.Model):
    device = models.ForeignKey(Device, on_delete=models.CASCADE, blank=True, null=True,verbose_name='Dispositivo')
    log = models.CharField(max_length=2500, blank=True, null=True, verbose_name='Log')
    alerta = models.BooleanField(verbose_name='Alerta')




#IPV4 to IPV6 View
class Segmento(models.Model):
    MASK = [
        ('8','255.0.0.0/8'),
        ('9', '255.128.0.0/9'),
        ('10', '255.192.0.0/10'),
        ('11', '255.224.0.0/11'),
        ('12', '255.240.0.0/12'),
        ('13', '255.248.0.0/13'),
        ('14', '255.252.0.0/14'),
        ('15', '255.254.0.0/15'),
        ('16', '255.255.0.0/16'),
        ('17', '255.255.128.0/17'),
        ('18', '255.255.192.0/18'),
        ('19', '255.255.224.0/19'),
        ('20', '255.255.240.0/20'),
        ('21', '255.255.248.0/21'),
        ('22', '255.255.252.0/22'),
        ('23', '255.255.254.0/23'),
        ('24', '255.255.255.0/24'),
        ('25', '255.255.255.128/25'),
        ('26', '255.255.255.192/26'),
        ('27', '255.255.255.224/27'),
        ('28', '255.255.255.240/28'),
        ('29', '255.255.255.248/29'),
        ('30', '255.255.255.252/30'),
        ('31', '255.255.255.254/31'),
        ('32', '255.255.255.255/32'),

    ]
    #Rango de direcciones ip 190.170.128.0/18
    rango = models.CharField(max_length=50, verbose_name='Rango IP')
    # Mascara de subred
    mascara = models.CharField(max_length=50, choices=MASK, verbose_name='Mascara')
    # Cantidad de direcciones IP
    direccion = models.IntegerField(verbose_name='Numero de usuarios', blank=True, null=True)
    # Segmentaciones de rangos IP 190.170.129.129/25 cantidades
    subredes = models.IntegerField(verbose_name='Numero de subredes', default=0, blank=True, null=True)
    # Reservadas IP
    reserv = models.IntegerField(blank=True, null=True, verbose_name='Numero de IP Reservadas')

    def save(self, *args, **kwargs):
        ip = IPNetwork(self.rango)
        subnets = list(ip.subnet(int(self.mascara)))
        super(Segmento, self).save(*args, **kwargs)

    def listadirecciones(self):
        ip = IPNetwork(self.rango)
        subnets = list(ip.subnet(int(self.mascara)))
        return list(subnets)

# Direcciones IP reservadas
class IpReservada(models.Model):
    ipv4 = models.GenericIPAddressField(protocol='IPv4', verbose_name='IPv4', blank=True, null=True)
    ipv6 = models.GenericIPAddressField(protocol='IPv6', verbose_name='IPv6', blank=True, null=True)
    mac = models.CharField(max_length=50, verbose_name='MAC')
    descripcion = models.TextField(verbose_name='Descripcion')
    dispositivo = models.ForeignKey(Device, on_delete=models.CASCADE, blank=True, null=True, verbose_name='Dispositivo')

class Solicitudes(models.Model):
    SOL = [
        ('0', 'Falla de conexion'),
        ('1', 'Expansion de red'),
        ('2', 'Solicitud de IP reservada'),
    ]
    usuario = models.CharField(max_length=50, verbose_name='Usuario')
    solicitud = models.CharField(max_length=200, choices=SOL, verbose_name='Tipo de Solicitud')
    descripcion = models.TextField(verbose_name='Descripcion')
    ubicacion = models.ForeignKey(Ubicacion, on_delete=models.SET_NULL, blank=True, null=True, verbose_name='Ubicacion')
    completa = models.BooleanField(default=False, verbose_name='Finalizada')
    creacion = models.DateTimeField(auto_created=True, auto_now=True)

    def solicitud_verbose(self):
        return dict(Solicitudes.SOL)[self.solicitud]



class SendConf(models.Model):
    devices = models.ManyToManyField(Device)
    conf = models.TextField(verbose_name='Configuracion a Enviar')

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect
from .forms import *
from .decorators import unauthenticated_user
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .models import *
# import netmiko
# import napalm
import sys
from time import sleep
import paramiko

# Create your views here.
def home_view(request):
    context = {}
    return render(request, 'accounts/home/home.html', context)


@unauthenticated_user
def LoginPage(request):
    if request.method =='POST':
        usernames = request.POST['username']
        passwords = request.POST['password']
        user = authenticate(request, username=usernames, password=passwords)
        if user is not None:
            login(request, user)
            # Redirect to a success page.
            return redirect('Dashboard')
        else:
            messages.info(request, 'Username or Password is Wrong')
    context = {}
    return render(request, 'accounts/home/login.html', context)


def LogoutUser(request):
    logout(request)
    return redirect('home')


@login_required(login_url='login')
def registration(request):
    form = CreateUserForm()
    if request.method =='POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')
            messages.success(request, 'La cuenta fue Creada '+ user)
            return redirect('login')
    context = {'form':form}
    return render(request, 'accounts/home/registration.html', context)


# @login_required(login_url='login')
def HomeSystem(request):
    countsr = Device.objects.filter(dvt='R').count()
    countsw = Device.objects.filter(dvt='S').count()
    countse = Device.objects.filter(dvt='ED').count()
    countsrw = Device.objects.filter(dvt='RW').count()
    solicitud = Solicitudes.objects.filter(completa=False).all()
    context = {
        'router':countsr,
        'switch':countsw,
        'endev': countse,
        'wifi':countsrw,
        'solicitudes':solicitud

    }
    return render(request, 'accounts/home/homesystem.html', context)


def SendConfiguration(request):
    form = SendConfForm(request.POST or None)
    if form.is_valid():
        obj = form.save()
        obj.user = request.user
        obj.save()
        for device in form.cleaned_data['devices']:
            print(device.dvt)
            conn = paramiko.SSHClient()
            conn.set_missing_host_key_policy(paramiko.AutoAddPolicy())
            conn.connect(device.ipv4, username=device.username, password=device.clave)
            router_conn = conn.invoke_shell()
            print('Successfully connected to')
            lineas = device.conf_t.splitlines()
            for linea in lineas:
                router_conn.send(linea)
                sleep(1)
                print(router_conn.recv(5000).decode("utf-8"))


    context = {"form": form}
    return render(request, 'accounts/sendconf.html', context)
def Ipv4Ipv6intro(request):
    context = {

    }
    return render(request, 'accounts/ipv4toipv6/intro.html', context)
def Ipv4Ipv6pasos(request):
    context = {

    }
    return render(request, 'accounts/ipv4toipv6/pasos.html', context)

def SegmentacionCalculadoraipv6(request):
    form = SegmentacionForm2(request.POST or None)
    objeto = None
    contar = 0
    if form.is_valid():
        obj = form.save()
        obj.user = request.user
        obj.save()
        objeto = Segmento.objects.last()

        #form = SegmentacionForm()
    context = {
        "form": form,
        "objetos":objeto,
        "contador":contar
    }
    return render(request, 'accounts/ipv4toipv6/segmentacion-calculadora.html', context)

def SegmentacionCalculadora(request):
    form = SegmentacionForm(request.POST or None)
    objeto = None
    if form.is_valid():
        obj = form.save()
        obj.user = request.user
        obj.save()
        objeto = Segmento.objects.last()
    context = {
        "form": form,
        "objetos":objeto,
    }
    return render(request, 'accounts/segmentacion-calculadora.html', context)



def Solicitudcrear(request):
    form = SolicitudForm(request.POST or None)
    if form.is_valid():
        obj = form.save()
        obj.user = request.user
        obj.save()
        form = SolicitudForm()
        redirect('home')
    context = {
        "form": form
    }
    return render(request, 'accounts/solicitud/solicitud.html', context)



def Solicitudver(request, pk):
    obj = get_object_or_404(Solicitudes, pk=pk)
    context = {
        "objeto": obj
    }
    return render(request, 'accounts/solicitud/solicitud-vista.html', context)

def Solicitudf(request, pk):
    obj = get_object_or_404(Solicitudes, pk=pk)
    if obj:
        obj.completa = True
        obj.save()
        redirect('Dashboard')
        return None
    return render(request, 'accounts/solicitud/solicitud-vista.html')

def InventarioListaDevice(request):
    objeto = Device.objects.all()
    context = {
        "objetos":objeto,
    }
    return render(request, 'accounts/device/inventario-lista.html', context)

def InventarioCrear(request):
    form = DeviceForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        form.save()
        return redirect('Inventario')
    template_name = 'accounts/device/device-crear.html'
    context = {'form': form}
    return render(request, template_name, context)

def InventarioUpdates(request, pk):
    obj = get_object_or_404(Device, pk=pk)
    form = DeviceForm(request.POST or None, instance=obj)
    formset = PuertoFormSet(request.POST or None, instance=obj)
    if form.is_valid() and formset.is_valid():
        formset.save()
        form.save()
        return redirect('Inventario')
    template_name = 'accounts/device/device-edit.html'
    context = {
        "form": form,
        "formset":formset,
        "object":obj
    }
    return render(request, template_name, context)

def IPListaReverse(request):
    objeto = IpReservada.objects.all()
    context = {
        "objetos":objeto,
    }
    return render(request, 'accounts/ipreservada/lista.html', context)

def IPCrear(request):
    form = IpReservadaForm(request.POST or None)
    if form.is_valid():
        obj = form.save()
        obj.user = request.user
        obj.save()
        return redirect('ip')
    template_name = 'accounts/ipreservada/crear.html'
    context = {'form': form}
    return render(request, template_name, context)

def IPUpdates(request, pk):
    obj = get_object_or_404(IpReservada, pk=pk)
    form = IpReservadaForm(request.POST or None, instance=obj)
    if form.is_valid():
        form.save()
        return redirect('ip')
    template_name = 'accounts/ipreservada/editar.html'
    context = {
        "form": form,
        "object": obj
    }
    return render(request, template_name, context)


def UbicacionLista(request):
    objeto = Ubicacion.objects.all()
    context = {
        "objetos":objeto,
    }
    return render(request, 'accounts/ubicacion/lista.html', context)

def UbicacionCrear(request):
    form = UbicacionForm(request.POST or None)
    if form.is_valid():
        obj = form.save()
        obj.user = request.user
        obj.save()
        form = UbicacionForm()
        return redirect('Lista Ubicacion')
    template_name = 'accounts/ubicacion/crear.html'
    context = {'form': form}
    return render(request, template_name, context)

def UbicacionUpdate(request, pk):
    obj = get_object_or_404(Ubicacion, pk=pk)
    form = UbicacionForm(request.POST or None, instance=obj)
    if form.is_valid():
        form.save()
        return redirect('Lista Ubicacion')
    template_name = 'accounts/ubicacion/editar.html'
    context = {
        "form": form,
        "object":obj,
    }
    return render(request, template_name, context)


def UbicacionBorrar(request, pk):
    obj = get_object_or_404(Ubicacion, pk=pk)
    obj.delete()
    print('se borro')
    return redirect('Lista Ubicacion')
    context = {
        "object": obj
    }
    return render(request, None, context)



def InventarioBorrar(request, pk):
    obj = get_object_or_404(Device, pk=pk)
    obj.delete()
    print('se borro')
    return redirect('Inventario')
    context = {
        "object": obj
    }
    return render(request, None, context)


def IPBorrar(request, pk):
    obj = get_object_or_404(IpReservada, pk=pk)
    obj.delete()
    print('se borro')
    return redirect('ip')
    context = {
        "object": obj
    }
    return render(request, None, context)

accounts/templates/accounts/home.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Telecom-home</title>
    <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/fonts/fontawesome-all.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/fonts/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/fonts/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/fonts/fontawesome5-overrides.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/Contact-Form-Clean.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/Features-Boxed.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/Footer-Basic.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/Footer-Dark.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/Highlight-Clean.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/Login-Form-Clean.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/Navigation-with-Button.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/Team-Boxed.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/Team-Clean.css' %}">
</head>

<body>
    <div>
        <nav class="navbar navbar-dark navbar-expand-md bg-dark navigation-clean-button">
            <div class="container"><a class="navbar-brand" href="#">TelecomSystemAdmin</a><button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse"
                    id="navcol-1">
                    <ul class="nav navbar-nav mr-auto"></ul><span class="navbar-text actions"> <a class="btn btn-light bg-warning action-button" role="button" href='{% url 'login' %}'>Login</a></span></div>
            </div>
        </nav>
    </div>
    <div class="highlight-clean">
        <div class="container">
            <div class="intro">
                <h2 class="text-center">Highlight</h2>
                <p class="text-center">Nunc luctus in metus eget fringilla. Aliquam sed justo ligula. Vestibulum nibh erat, pellentesque ut laoreet vitae. </p>
            </div>
            <div class="buttons"><a class="btn btn-warning" role="button" href="#" style="background-color: #ffc107;">Primary</a><button class="btn btn-light" type="button">Secondary</button></div>
        </div>
    </div>
    <div class="features-boxed" style="background-color: #ffffff;">
        <div class="container">
            <div class="intro">
                <h2 class="text-center">Features </h2>
                <p class="text-center">Nunc luctus in metus eget fringilla. Aliquam sed justo ligula. Vestibulum nibh erat, pellentesque ut laoreet vitae.</p>
            </div>
            <div class="row justify-content-center features">
                <div class="col-sm-6 col-md-5 col-lg-4 item">
                    <div class="box"><i class="fab fa-docker icon" style="color: rgb(255,193,7);"></i>
                        <h3 class="name">Works everywhere</h3>
                        <p class="description">Aenean tortor est, vulputate quis leo in, vehicula rhoncus lacus. Praesent aliquam in tellus eu.</p><a class="learn-more" href="#" style="color: rgb(255,193,7);">Learn more »</a></div>
                </div>
                <div class="col-sm-6 col-md-5 col-lg-4 item">
                    <div class="box"><i class="fab fa-python icon" style="color: rgb(255,193,7);"></i>
                        <h3 class="name">Always available</h3>
                        <p class="description">Aenean tortor est, vulputate quis leo in, vehicula rhoncus lacus. Praesent aliquam in tellus eu.</p><a class="learn-more" href="#" style="color: #ffc107;">Learn more »</a></div>
                </div>
                <div class="col-sm-6 col-md-5 col-lg-4 item">
                    <div class="box"><i class="fas fa-network-wired icon" style="color: #ffc107;"></i>
                        <h3 class="name">Customizable </h3>
                        <p class="description">Aenean tortor est, vulputate quis leo in, vehicula rhoncus lacus. Praesent aliquam in tellus eu.</p><a class="learn-more" href="#" style="color: #ffc107;">Learn more »</a></div>
                </div>
                <div class="col-sm-6 col-md-5 col-lg-4 item">
                    <div class="box"><i class="fab fa-github icon" style="color: rgb(255,193,7);"></i>
                        <h3 class="name">Organic </h3>
                        <p class="description">Aenean tortor est, vulputate quis leo in, vehicula rhoncus lacus. Praesent aliquam in tellus eu.</p><a class="learn-more" href="#" style="color: #ffc107;">Learn more »</a></div>
                </div>
                <div class="col-sm-6 col-md-5 col-lg-4 item">
                    <div class="box"><i class="far fa-hdd icon" style="color: #ffc107;"></i>
                        <h3 class="name">Fast </h3>
                        <p class="description">Aenean tortor est, vulputate quis leo in, vehicula rhoncus lacus. Praesent aliquam in tellus eu.</p><a class="learn-more" href="#" style="color: #ffc107;">Learn more »</a></div>
                </div>
                <div class="col-sm-6 col-md-5 col-lg-4 item">
                    <div class="box"><i class="fas fa-signal icon" style="color: #ffc107;"></i>
                        <h3 class="name">Mobile-first</h3>
                        <p class="description">Aenean tortor est, vulputate quis leo in, vehicula rhoncus lacus. Praesent aliquam in tellus eu.</p><a class="learn-more" href="#" style="color: #ffc107;">Learn more »</a></div>
                </div>
            </div>
        </div>
    </div>
    <div class="team-clean">
        <div class="container d-inline">
            <div class="intro">
                <h2 class="text-center">Team </h2>
                <p class="text-center">Nunc luctus in metus eget fringilla. Aliquam sed justo ligula. Vestibulum nibh erat, pellentesque ut laoreet vitae. </p>
            </div>
            <div class="row justify-content-center people">
                <div class="col-md-6 col-lg-4 item" style="width: 416px;"><img class="rounded-circle" src="{% static 'assets/img/1.jpg' %}">
                    <h3 class="name">Julio Moreno</h3>
                    <p class="title">Desarrollador</p>
                    <p class="description">Aenean tortor est, vulputate quis leo in, vehicula rhoncus lacus. Praesent aliquam in tellus eu gravida. Aliquam varius finibus est, et interdum justo suscipit id. Etiam dictum feugiat tellus, a semper massa. </p>
                    <div class="social"><a href="#"><i class="fa fa-linkedin"></i></a><a href="#"><i class="fa fa-twitter"></i></a><a href="#"><i class="fa fa-instagram"></i></a></div>
                </div>
            </div>
        </div>
    </div>
    <div class="text-info contact-clean" style="background-color: #ffffff;">
        <form method="post">
            <h2 class="text-center">Contact me</h2>
            <div class="form-group"><input class="form-control" type="text" name="name" placeholder="Name"></div>
            <div class="form-group"><input class="form-control" type="email" name="email" placeholder="Email"></div>
            <div class="form-group"><textarea class="form-control" name="message" placeholder="Message" rows="14"></textarea></div>
            <div class="form-group"><button class="btn btn-warning btn-block" type="submit" style="background-color: #ffc107;">send </button>
                <div id="Space">
                    <div id="Space"></div>
                    <div></div>
                </div>
            </div>
        </form>
    </div>
    <div class="text-warning bg-dark footer-basic">
        <footer>
            <div class="social"><a href="#"><i class="icon ion-social-instagram"></i></a><a href="#"><i class="icon ion-social-twitter"></i></a><a href="#"><i class="icon ion-email"></i></a><a href="#"><i class="icon ion-social-linkedin"></i></a></div>
            <p class="copyright">Company Name © 2017</p>
        </footer>
    </div>

    <script src="{% static 'assets/js/jquery.min.js' %}"></script>
    <script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
</body>

</html>

accounts/templates/accounts/inventario-lista.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block head_title %} Vista Inventario {% endblock %}
{% block title_page %} Equipos Dentro de la red {% endblock %}


{% block content %}
    <div class="card shadow">
    <div class="card-header py-3">
        <h5 class="text-warning m-0 font-weight-bold">Iventario de equipos</h5>
                <a href="{% url 'crear dispositivo' %}" class="btn btn-warning btn-lg active btn-sm" role="button" aria-pressed="true">Crear Dispositivo</a>

    </div>

    <div class="card-body">
        <div class="table-responsive table mt-2" id="dataTable" role="grid" aria-describedby="dataTable_info">
            <table class="table my-0" id="dataTable">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Dispositivo</th>
                        <th>Marca</th>
                        <th>Modelo</th>
                        <th>Ubicacion</th>
                        <th>Puertos</th>
                        <th>Ipv4 de acceso</th>
                        <th>Ipv6 de acceso</th>
                    </tr>
                </thead>
                <tbody>

                {% for objeto in objetos %}
                    <tr>
                        <td>{{ objeto.id }} </td>
                        <td>{{ objeto.get_dvt_display }}</td>
                        <td>{{ objeto.marca }}</td>
                        <td>{{ objeto.modelo }}</td>
                        <td>{{ objeto.ubicacion }}</td>
                        <td>{{ objeto.puerto_set.count }}</td>
                        <td>{{ objeto.ipv4 }}</td>
                        <td>{{ objeto.ipv6 }}</td>
                    </tr>
                {% endfor %}
                </tbody>

            </table>

        </div>

    </div>
</div>

{% endblock %}

accounts/templates/accounts/sendconf.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% load widget_tweaks %}
{% block head_title %} Configuracion{% endblock %}
{% block title_page %} Enviar Configuracion{% endblock %}


{% block content %}

    {% bootstrap_javascript jquery='full' %}
    {% bootstrap_messages %}

<div class="row">
<div class="col-lg-6 mb-4">

<form method='POST' action='.'>
    {% csrf_token %}
{% bootstrap_form_errors form %}
    <div class="btn-group" data-toggle="buttons">
{% for checkbox in form.devices %}
    <label class="btn btn-warning">
    {{ checkbox.tag }} {{ checkbox.choice_label }}
    </label>
{% endfor %}
</div>

{% bootstrap_field form.conf layout='horizontal' %}



    <div class="form-group">
        <input class="btn btn-warning btn-block" type="submit" value="Enviar Configuracion"></input>
    </div>
</form>
</div>
</div>






{% endblock %}